name: 'Release gatekeeper check'
description: 'Checks if PR has approves from release GK team'
inputs:
  github-token:  # token
    description: 'Github secret token'
    required: true
    default: 'missing-token'
runs:
  using: 'node12'
  main: 'index.js'